dataCleaning = LimpiezaDatos('Ejercicio1/Datasets/activaciones_samur_2023.csv')
dataCleaning.copia()
dataCleaning.limpieza_nulos()
dataCleaning.limpieza_duplicados()
dataCleaning.limpieza_atipicos()
dataCleaning.guardar()